title: Başlık(title)
author: val-ea
email: your-email@domain.com
description: > # açıklama
theme: jekyll-theme-hack

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
